# 博客配置 | Blog Configuration
# keywords:
author: Bokuan Li
description: Math student.

# 如需修改icon,请替换 source/images/favicon.ico 文件
# If you want to change the icon, please replace the source/images/favicon.ico file
avatar: /images/favicon.ico
copyright: 2025

# 个人信息 | Personal Information
name: Bokuan Li

# 社交账号 | Social Account
github: jerry-licious
mail: bokuan.li0@gmail.com
mail_sanetised: bokuan [dot] li0 [at] gmail [dot] com
overleaf: https://oce.jerrylicious.me
obsidian: https://garden.jerrylicious.me
resume: https://jerrylicious.me/bokuan-li-cv.pdf
# linkedin: https://linkedin.com/in/xxx
# QQ: http://sighttp.qq.com/authd?IDKEY=xxx

# TODO：适配更多的社交账号
# TODO: Add more social accounts
